spring.application.name=weatherApi
weather.api.key=20e497c1bcea421896a20339251708
weather.api.Url=http://api.weatherapi.com/v1/current.json
weather.api.forecast.Url=http://api.weatherapi.com/v1/forecast.json
